spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testzhang?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
  mvc:
    view:
      prefix: /
      suffix: .HTML
  redis:
    host: 122.112.201.113
    port: 6379
    #redis超时时间（毫秒），如果不设置，取默认值2000
    timeout: 6000
    database: 15
server:
  port: 8901



