server:
  port: 8902
spring:
  application:
    name: mySpringBoot-JPA
  datasource:
    url: jdbc:mysql://localhost:3306/testzhang?characterEncoding=utf-8&useSSL=true&serverTimezone=GMT
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
  mvc:
    view:
      prefix: /
      suffix: .HTML
  redis:
    host: 122.112.201.113
    port: 6379
    #redis超时时间（毫秒），如果不设置，取默认值2000
    timeout: 6000
    database: 15
  rabbitmq:
    host: 122.112.201.113

    username: admin
    password: admin
    virtual-host: /
    port: 5672
  # servlet 上传
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

elaticjob:
  zookeeper:
    server-lists: 127.0.0.1:2181
    namespace: myjpa-job3

file:
  filepath: C:/Users/user/Downloads/

